# Generated by Django 3.1.7 on 2021-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0003_auto_20210323_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
                ('group', models.CharField(choices=[('PH', 'Physical'), ('SP', 'Spiritual'), ('FI', 'Financial'), ('OC', 'Occupational'), ('PE', 'Personal'), ('NA', 'NA')], default='NA', max_length=2)),
                ('max_complete', models.SmallIntegerField()),
                ('value', models.IntegerField()),
                ('max_points', models.IntegerField()),
                ('frequency', models.SmallIntegerField()),
                ('time_freq', models.CharField(choices=[('DAY', 'Day'), ('MTH', 'Month'), ('YER', 'Year'), ('IDK', 'Choose')], default='IDK', max_length=3)),
            ],
        ),
    ]
