# Generated by Django 3.1.7 on 2021-03-25 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wellness', '0004_allactivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ftid',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.RenameModel(
            old_name='AllActivities',
            new_name='Activity',
        ),
        migrations.CreateModel(
            name='CompletedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('date', models.DateTimeField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wellness.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
