# Generated by Django 3.1.7 on 2021-03-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0007_auto_20210325_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
                ('text', models.TextField(blank=True, max_length=500)),
                ('start', models.DateField(blank=True)),
                ('end', models.DateField(blank=True)),
                ('interval', models.IntegerField()),
                ('check', models.BooleanField()),
            ],
        ),
    ]
