# Generated by Django 3.1.7 on 2021-03-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0008_reminders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminders',
            name='name',
        ),
    ]
